[package]
name = "taurino-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
taurino-core = { version = "0.1.0", git = "https://github.com/taurino-foundation/taurino-core" }
taurino-menu = { version = "0.1.0", git = "https://github.com/taurino-foundation/taurino-menu" }
taurino-window = { version = "0.1.0", git = "https://github.com/taurino-foundation/taurino-window" }
taurino-trayicon = { version = "0.1.0", git = "https://github.com/taurino-foundation/taurino-trayicon" }
serde_with = "3.24.0"
url = { version = "2.5.8",  features = [
	"serde",
]}