use crate::window::events::{WindowEvent, WindowEventWrapper};
/// Central event dispatcher and lifecycle coordinator for the engine.
///
/// `EngineEventHandler` receives all events produced by the Tao event loop and
/// translates them into engine-level operations.
///
/// It is responsible for coordinating two distinct lifecycles:
///
/// - **window lifecycle** — creation-independent events, close requests and
///   destruction of individual windows;
/// - **application lifecycle** — process shutdown and termination of the Tao
///   event loop.
///
/// # Event categories
///
/// The handler currently processes:
///
/// - [`WindowEvent`] values originating from native windows;
/// - [`EventLoopMessage`] values generated by Taurino subsystems or external
///   process events;
/// - Tao lifecycle events such as [`Event::LoopDestroyed`].
///
/// Events that are not relevant to the engine lifecycle are ignored.
///
/// # Shutdown synchronization
///
/// `shutting_down` acts as an idempotency guard.
///
/// Application shutdown may be requested by several independent sources, for
/// example:
///
/// - Ctrl+C;
/// - SIGTERM;
/// - closing the final application window;
/// - an explicit application exit command.
///
/// The atomic guard ensures that global cleanup is executed at most once even
/// when several shutdown sources occur close together.
///
/// # Locking
///
/// Manager locks must be held for the shortest possible duration.
///
/// In particular, callbacks and cleanup routines must not run while the
/// `WindowManager` lock is held because those operations may acquire other
/// manager locks themselves. Releasing the original lock before invoking such
/// operations avoids unnecessary lock nesting and potential deadlocks.
use crate::{log_if_err, manager::EngineManager};
use anyhow::{Result, anyhow};
use std::fmt::{Debug, Formatter};
use std::{
    ops::Deref,
    pin::Pin,
    sync::{
        Arc,
        atomic::{AtomicBool, Ordering},
    },
};
use taurino_core::{
    anyhow,
    tao::{
        event::Event,
        event_loop::{ControlFlow, EventLoop, EventLoopBuilder, EventLoopWindowTarget},
        window::WindowId as TaoWindowId,
    },
};

/// Internal messages delivered through the Tao user-event channel.
///
/// These messages provide a thread-safe mechanism for scheduling engine work on
/// the event-loop thread.
///
/// Code executing outside the GUI event loop should generally send one of these
/// messages instead of manipulating Tao state directly.
pub enum EventLoopMessage {
    /// Requests graceful termination of the entire application.
    ///
    /// The request is processed by [`EngineEventHandler`] on the event-loop
    /// thread.
    Shutdown,

    /// Executes a dynamically supplied Taurino event-loop operation.
    ///
    /// This variant allows engine subsystems to schedule arbitrary operations
    /// that require access to the Tao event-loop target and its
    /// [`ControlFlow`].
    OnMainThread(TaurinoEvent),
}
pub type TaurinoLoop = EventLoop<EventLoopMessage>;
pub type TaurinoLoopBuilder = EventLoopBuilder<EventLoopMessage>;
pub type TaurinoWindowTarget = EventLoopWindowTarget<EventLoopMessage>;
// pub type TaurinoLoopProxy = EventLoopProxy<EventLoopMessage>;
// pub type TaurinoLoopClosed = EventLoopClosed<EventLoopMessage>;
pub type TaurinoLoopEvent<'a> = Event<'a, EventLoopMessage>;

pub type TaurinoCallback = Pin<Box<dyn Fn(&TaurinoWindowTarget, &mut ControlFlow) -> Result<()> + Send>>;

/// Type-erased operation scheduled for execution on the Tao event-loop thread.
///
/// The callback receives:
///
/// - the current [`TaurinoWindowTarget`], allowing creation or manipulation of
///   event-loop-bound objects;
/// - mutable [`ControlFlow`], allowing the callback to influence future
///   event-loop execution.
///
/// The callback is `Send` because it may be created on another thread before
/// being transported through the Tao user-event channel.
///
/// It is boxed and pinned to provide one stable, type-erased representation for
/// arbitrary callback implementations.
///
pub struct TaurinoEvent(TaurinoCallback);

impl Debug for TaurinoEvent {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TaurinoEvent").finish()
    }
}

impl TaurinoEvent {
    pub fn new<F: Fn(&TaurinoWindowTarget, &mut ControlFlow) -> Result<()> + Send + 'static>(f: F) -> Self {
        Self(Box::pin(f))
    }
}

impl Deref for TaurinoEvent {
    type Target = Pin<Box<dyn Fn(&TaurinoWindowTarget, &mut ControlFlow) -> Result<()> + Send>>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
pub struct EngineEventHandler {
    /// Shared access to all engine subsystem managers.
    manager: Arc<EngineManager>,

    /// Indicates whether application shutdown has already started.
    ///
    /// Atomic synchronization is used because shutdown requests may originate
    /// from multiple runtime paths.
    shutting_down: AtomicBool,
}

impl EngineEventHandler {
    pub fn new(manager: Arc<EngineManager>) -> Self {
        Self {
            manager,
            shutting_down: AtomicBool::new(false),
        }
    }

    pub fn handle_event<'a>(
        &self,
        event: TaurinoLoopEvent<'a>,
        _target: &TaurinoWindowTarget,
        control_flow: &mut ControlFlow,
    ) {
        if self.shutting_down.load(Ordering::Acquire) {
            return;
        }

        let loop_destroyed = matches!(&event, taurino_core::tao::event::Event::LoopDestroyed);

        let result = (|| -> Result<()> {
            if !matches!(*control_flow, ControlFlow::ExitWithCode(_)) {
                *control_flow = ControlFlow::Wait;
            }

            match event {
                taurino_core::tao::event::Event::WindowEvent { event, window_id, .. } => {
                    self.handle_window_event(event, window_id, control_flow)?;
                }

                taurino_core::tao::event::Event::UserEvent(message) => {
                    self.handle_user_message(message, _target, control_flow)?;
                }

                _ => {}
            }

            Ok(())
        })();

        log_if_err!(result);

        if (loop_destroyed || matches!(*control_flow, ControlFlow::ExitWithCode(_)))
            && !self.shutting_down.swap(true, Ordering::AcqRel)
        {
            // Global shutdown cleanup can be performed here.
        }
    }

    fn handle_user_message(
        &self,
        message: EventLoopMessage,
        _target: &TaurinoWindowTarget,
        control_flow: &mut ControlFlow,
    ) -> Result<()> {
        match message {
            EventLoopMessage::Shutdown => {
                self.shutdown(control_flow)?;
            }

            EventLoopMessage::OnMainThread(event) => {
                event(_target, control_flow)?;
            }
        }

        Ok(())
    }

    fn handle_window_event(
        &self,
        event: taurino_core::tao::event::WindowEvent<'_>,
        window_id: TaoWindowId,
        control_flow: &mut ControlFlow,
    ) -> Result<()> {
        use taurino_core::tao::event::WindowEvent as TaoWindowEvent;

        // Destroyed kann kommen, nachdem das Window schon entfernt wurde.
        if matches!(event, TaoWindowEvent::Destroyed) {
            return self.handle_window_destroyed(window_id, control_flow);
        }

        // CloseRequested wird vom Wrapper nicht gemappt -> vorab behandeln.
        if matches!(event, TaoWindowEvent::CloseRequested { .. }) {
            let window = {
                let window_manager = self.manager.window()?;
                window_manager
                    .get_by_tao_id(window_id)
                    .cloned()
                    .ok_or_else(|| anyhow!("window with Tao id {window_id:?} not found"))?
            };

            let window_label = window.label.clone();

            // Tao hat keinen signal_tx; wir erzeugen einen eigenen Kanal,
            // falls ein Consumer das Schließen verhindern will.
            let (signal_tx, signal_rx) = std::sync::mpsc::channel::<bool>();

            self.manager
                .emit_global_window_event(window_label.clone(), WindowEvent::CloseRequested { signal_tx })?;

            // Wenn der Consumer `true` sendet, wird nicht geschlossen.
            if let Ok(prevent) = signal_rx.try_recv() {
                if prevent {
                    return Ok(());
                }
            }

            self.close_window(window_id, &window_label, control_flow)?;
            return Ok(());
        }

        // Window auflösen, Lock sofort freigeben.
        let window = {
            let window_manager = self.manager.window()?;
            window_manager
                .get_by_tao_id(window_id)
                .cloned()
                .ok_or_else(|| anyhow!("window with Tao id {window_id:?} not found"))?
        };

        let window_label = window.label.clone();

        // Tao-Event -> Taurino-WindowEvent
        let Some(event) = WindowEventWrapper::parse(&window, &event).0 else {
            return Ok(());
        };

        // Direkt die Enum-Variante emitten — kein format!/&str mehr.
        self.manager.emit_global_window_event(window_label, event)?;

        Ok(())
    }

    fn handle_window_destroyed(&self, window_id: TaoWindowId, control_flow: &mut ControlFlow) -> Result<()> {
        // The window may already have been removed by CloseRequested.
        //
        // In that case Destroyed is only the native confirmation and
        // must not be treated as another cleanup failure.
        let window = {
            let mut window_manager = self.manager.window()?;
            window_manager.remove_by_tao_id(window_id)
        };

        let Some(window) = window else {
            return Ok(());
        };

        let window_label = window.label.clone();

        self.manager
            .emit_global_window_event(window_label.clone(), WindowEvent::Destroyed)?;

        self.cleanup_window_resources(&window_label)?;

        if window_label == "main" {
            *control_flow = ControlFlow::Exit;
        }

        Ok(())
    }

    fn close_window(&self, window_id: TaoWindowId, window_label: &str, control_flow: &mut ControlFlow) -> Result<()> {
        // Remove the window while holding only the WindowManager lock.
        let removed_window = {
            let mut window_manager = self.manager.window()?;

            window_manager.remove_by_tao_id(window_id)
        };

        // The manager lock has been released at this point.
        //
        // Cleanup of other managers must happen afterwards so that
        // manager locks are never unnecessarily nested.
        if removed_window.is_some() {
            self.cleanup_window_resources(window_label)?;
        }
        // Exit the event loop once no windows remain.
        let no_windows_left = {
            let window_manager = self.manager.window()?;
            window_manager.is_empty()
        };

        if no_windows_left {
            *control_flow = ControlFlow::Exit;
        }
        Ok(())
    }

    fn cleanup_window_resources(&self, _window_label: &str) -> Result<()> {
        //
        // Add cleanup for managers that own window-specific resources.
        //
        // Examples:
        //
        // self.manager.trayicon()?.destroy_for_window(window_label)?;
        // self.manager.menu()?.remove_window_menu(window_label)?;
        //
        // Do NOT hold WindowManager's MutexGuard while doing this.
        //

        Ok(())
    }

    fn cleanup_app_resources(&self) -> Result<()> {
        //
        // Add cleanup for managers that own app-specific resources.

        //
        // Do NOT hold WindowManager's MutexGuard while doing this.
        //

        Ok(())
    }

    fn shutdown(&self, control_flow: &mut ControlFlow) -> Result<()> {
        // Idempotent: Shutdown darf nur einmal wirklich ausgeführt werden.
        if self.shutting_down.swap(true, Ordering::AcqRel) {
            return Ok(());
        }

        // Zuerst alle Windows aus dem WindowManager herausnehmen.
        //
        // Wichtig:
        // Nicht während cleanup_window_resources() den WindowManager-Lock halten.
        let windows = {
            let mut window_manager = self.manager.window()?;

            let labels = window_manager.labels().map(str::to_owned).collect::<Vec<_>>();

            window_manager.clear();

            labels
        };

        // WindowManager-Lock ist hier bereits frei.
        for window_label in windows {
            log_if_err!(self.cleanup_window_resources(&window_label));

            log_if_err!(
                self.manager
                    .emit_global_window_event(window_label, WindowEvent::Destroyed)
            );
        }

        self.cleanup_app_resources()?;

        *control_flow = ControlFlow::Exit;

        Ok(())
    }
}
